### ISSUE TITLE
TypeError: unsupported operand type(s) for ^: 'SingleUnits' and 'int'

### ISSUE THREAD

**Issue by tempdeltavalue** [LubomyrIvanitskiy/unitates#1]
<img width="1014" alt="Screenshot 2022-07-11 at 23 47 24" src="https://user-images.githubusercontent.com/36921178/178355340-2c060e6a-d45d-4a9c-806c-74c5ae723fd3.png">

https://colab.research.google.com/drive/1yNsKakByQUSTzz0yBLUp-1IJnnbxkkO_?usp=sharing

**Comment by LubomyrIvanitskiy** [comment]
Thank you for your attention to this library.
Raising to the power using 'Bitwise XOR' operator is not the pythonic way. Try to use standart ** operator instead.
Also make  sure you have the latest and greatest version installed (for now it's 1.0.13).
![image](https://user-images.githubusercontent.com/30999506/178439635-8e80acb2-dd00-413d-8cc7-500d68b858ec.png)

**Comment by tempdeltavalue** [comment]
@LubomyrIvanitskiy can you share a colab?

also not obvious why do you need this part of init
![Screenshot from 2022-07-12 16-06-10](https://user-images.githubusercontent.com/36921178/178496991-5495d86f-c793-4d1a-b02e-5a4fc6c2a43b.png)

**Comment by LubomyrIvanitskiy** [comment]
Sure.
https://colab.research.google.com/drive/1yNsKakByQUSTzz0yBLUp-1IJnnbxkkO_?usp=sharing

**Comment by tempdeltavalue** [comment]
@LubomyrIvanitskiy :( You did move your project into package but now it's inconvenient to experiment with your code

**Comment by tempdeltavalue** [comment]
@LubomyrIvanitskiy  
git doesn't display **2 properly :( 

I tried to got G in this way
r = m   #<--- reference/value ?
F=kg*m/sec**2
m = kg   #<--- reference/value ?

# F = G (m^2/r^2)
G = F  / m^2  / r^2
G = F * r^2 / m^2 

1 kg^2/sec^2 and got wrong output (^ - is strange here because you don't support that) but should be m^3⋅kg^−1⋅s^−2

maybe something wrong with my formula (but it's simple gravity law, I guess (m1= m2))

**Comment by LubomyrIvanitskiy** [comment]
I believe you have missed up names of the variables in the Gravity Constant formula and the units. 
The value of G is (6.6743 ± 0.00015) × 10−11 m^3*k^-1*s^−2.
So m^3*kg^-1*s^−2 == m^3/(kg*s^2). This is exactly the unit I demonstrated in the provided colab.

**Comment by tempdeltavalue** [comment]
You type it by hand ... but same units should be produced by this formula 
G = F * r^2 / m^2

please check your colab for more details 
https://colab.research.google.com/drive/1yNsKakByQUSTzz0yBLUp-1IJnnbxkkO_?usp=sharing

**Comment by tempdeltavalue** [comment]
It was my mistake ... sorry
